### ISSUE TITLE
Some issues on your map

### ISSUE THREAD

**Issue by Binnette** [cedricguadalupe/FRANCE-COVID-19#2]
Hi @cedricguadalupe,

Thanks a lot for your dashboard. It is very helpful and visual!

Where did you find all those data? I visited website https://www.santepubliquefrance.fr but I only found 4 PDF file for march 4, 5, 6 and 7. Do you have a link to the complete dataset? Or do you collect manually the data on the website every-days? 

Here are some "improvements" you can make on your map:

### Change labels in popups (map & diagram)

- Replace "Region_Code" by "Region"
- Replace "Max de Confirmed" by "Confirmed"
- Replace "Max de Death" by "Death"

![image](https://user-images.githubusercontent.com/6597721/76470654-0166bd80-63f1-11ea-9855-ce601cd176dd.png)

![image](https://user-images.githubusercontent.com/6597721/76472091-db431c80-63f4-11ea-82ed-2532bac7911f.png)

**Comment by cedricguadalupe** [comment]
I collect manually the data on the website every-days. Sorry for the wrong labels, I'm French and metabase adds words in french in the dashboard.
