### ISSUE TITLE
Wrong numbers in the 'Death' column of the 'Confirmd cases by region' table

### ISSUE THREAD

**Issue by paulRbr** [cedricguadalupe/FRANCE-COVID-19#6]
Hello @cedricguadalupe, thanks for your work on this!

I think there's an error in the numbers displayed in the `Confirmed Cases by Region` table in your metabase dashboard.

The total of death seems to be working, however the `death` column in that table seems wrong. (I mean it would be great if it was the real numbers, but I don't think it is).

Do you have the dashboard defined as code so we can send you a pull request? (If you do it manually that's fine too of course.)

Thanks again and have stay safe

**Comment by cedricguadalupe** [comment]
I don't have region numbers for death and recovered

**Comment by cedricguadalupe** [comment]
If you find missing data from geodes, sante publique france or ARS, please pull request missing data?
