### ISSUE TITLE
Inconsistencies in the data

### ISSUE THREAD

**Issue by NavinSangtani** [cedricguadalupe/FRANCE-COVID-19#8]
First: 
The data for 27/03/2020 seems to be duplicated from 26/03/2020 for the confirmed dataset. 

Second:
I've noticed that the sum of all data of the regions does not match with the total cases column. 
For example if you take the data for 26/03/2020
Confirmed: Total Column = 32964 ; Sum of Regions = 25903
Recovered:  Total Column = 4948 ; Sum of Regions = 4967
Deaths: Total Column = 1696 ; Sum of Regions = 1704
I have checked all the dates and the issue appears in all three datasets on multiple dates. Can you explain why this is?

**Comment by cedricguadalupe** [comment]
We have no data for confirmed by region and recovered/death we have data from geodes for region and spf for total

**Comment by cedricguadalupe** [comment]
I keep the same value of last day when I have no data for a region

**Comment by cedricguadalupe** [comment]
If you find missing data, you could pull request?
